---

- include_tasks: prep.yaml

# A kubernetes (or OpenShift) host and an API key must be set.
# We will either have authenticated against an OpenShift server
# or the AWX kubernetes credentials will have injected suitable
# values for the K8S_AUTH_HOST and K8S_AUTH_API_KEY environment variables.
# Either way the ansible variables 'k8s_auth_host' and
# 'k8s_auth_api_key' will have been set.
- name: Assert authentication
  assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_auth_api_key|length > 0
  when: k8s_auth_kubeconfig|length == 0

- name: Ensure recovery PVC
  block:

  # Create a recovery PVC

  - name: Create recovery PVC
    k8s:
      definition: "{{ lookup('template', 'pvc.yaml.j2') }}"
      wait: yes

  when: recovery_volume_size_g|int > 0

- name: Use pre-existing recovery PVC
  block:

  # The PVC must exist

  - name: Check recovery PVC
    k8s_info:
      kind: PersistentVolumeClaim
      api_version: v1
      namespace: "{{ recovery_namespace }}"
      name: "{{ recovery_volume_pvc }}"
    register: pvc_result

  - name: Assert recovery PVC
    assert:
      that: pvc_result.resources|length == 1

  when: recovery_volume_size_g|int == 0

# Go...

- block:

  - include_tasks: deploy.yaml

  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
