---

# Do we need to add kubernetes modules?
# On some older AWX servers we do.
backup_control_needs_kubernetes: no

# Maximum time to wait for a (one-time) backup to complete
backup_job_timeout_minutes: 20
