---

recovery_image_registry: ''
recovery_image: informaticsmatters/sql-recovery
recovery_image_tag: stable

# CPU and Memory requests and limits.
# Limits can be set to 0 to avoid them being defined in the Pod.
recovery_cpu_request: 250m
recovery_cpu_limit:
recovery_mem_request: 100Mi
recovery_mem_limit:

# General timeout,
# typically used within the k8s module for wait durations.
# One of the most time-consuming containers to start is Keycloak,
# which may take 7 minutes or so to become ready.
wait_timeout: 600
# Wait for volume binding?
# Probably unless multi-zone deployments
# where the PVC will not bind until the 'consumer' pod appears.
wait_for_bind: no
# Volume binding timeout (seconds)
bind_timeout: 60

# Names of kesy in the database Secret
recovery_database_admin_user: postgres
recovery_database_secret_admin_user_password_key: root_password
