---

# The namespace containing the database that will be used to recover to.
# The namespace is expected to have a suitable service account.
#
# If a docker-hub PullSecret is expected than it is assumed that it
# already exists in the namespace and is attached to the service account.
recovery_namespace: SetMe
recovery_sa: postgres
recovery_host: postgres

# The backup to recover.
# See the sql-recovery implementation for options.
recovery_from: latest
# The expected number of databases after the recovery is complete.
# This can be used in automated backup testing as a crude
# extra-confidence check on the restoration.
# By setting this value to a positive non-zero value you force
# the recovery container to count the databases and error if
# it does not match the value you provided.
recovery_database_expected_count: 0
# The maximum age of the latest backup?
# If you set this (1 or higher) the recovery image checks the latest backup
# is not older than the value you provide.
#
# Allow some wiggle-room here. If you're backing up every 6 hours
# take account of the time it takes to complete the backup, it might take
# a few minutes or an hour or two. As a general rule, set this to twice the
# backup period. If you're backing up every 6 hours, set this value to 12.
recovery_latest_backup_maximum_age_h: 0

# Do not stop on error?
# If set the recovery Pod's DO_NOT_STOP_ON_ERROR variable is set.
recovery_do_not_stop_on_error: no

# Wait for recovery to finish?
# Set to 0 so as not to wait.
recovery_wait_minutes: 60

# Database (admin) credentials are in a secret in the namespace.
# The admin user and password are expected in the secret's: -
# - database_admin_user
# - database_admin_user_password
# We just need to supply the name of the Secret.
recovery_secret: postgres

# If the backup source is S3 you need to name the bucket.
# You cannot define a bucket and a claim name.
recovery_s3_bucket: ''
recovery_s3_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
recovery_s3_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
# If the backup source is a volume you need to provide the claim name.
# You cannot define a claim name and a bucket.
recovery_volume_pvc_name: ''
